
# NumPy Assignment — Array Attributes, Indexing & Slicing



# Q1. Array Attributes

## Problem Statement
Create the following NumPy array:

```python
[10, 20, 30, 40, 50]
```

Print:
- Shape
- Number of Dimensions
- Size
- Data Type

## Sample Output
```python
Shape: (5,)
Dimensions: 1
Size: 5
dtype: int64
```


In [6]:
# Write your code here
import numpy as np
arr =np.arange(10,51,10)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Find Array Shape

## Problem Statement
Create the following array:

```python
[[1,2,3],
 [4,5,6]]
```

Print only the shape of the array.

## Sample Output
```python
(2, 3)
```


In [8]:
# Write your code here
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])


# Q3. 1D Indexing

## Problem Statement
Create the array:

```python
[5, 10, 15, 20, 25]
```

Print:
- First element
- Last element

## Sample Output
```python
5
25
```


In [9]:
# Write your code here
arr = np.arange(5,26,5)
arr

array([ 5, 10, 15, 20, 25])


# Q4. 2D Indexing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the element `50`.

## Sample Output
```python
50
```


In [10]:
# Write your code here
arr = np.arange(10,91,10).reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])


# Q5. 2D Indexing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the element `9`.

## Sample Output
```python
9
```


In [16]:
# Write your code here
arr = np.arange(1,10).reshape(3,3)
arr[2,2]

np.int64(9)


# Q6. 1D Slicing

## Problem Statement
Create the array:

```python
[10,20,30,40,50,60]
```

Print elements from index 1 to 4.

## Sample Output
```python
[20 30 40 50]
```


In [26]:
# Write your code here
arr = np.arange(10,51,10)
arr[1:5]

array([20, 30, 40, 50])


# Q7. 1D Slicing

## Problem Statement
Create the array:

```python
[1,2,3,4,5,6,7,8]
```

Print the first 5 elements.

## Sample Output
```python
[1 2 3 4 5]
```


In [28]:
# Write your code here
arr = np.arange(1,9)
arr[0:5]

array([1, 2, 3, 4, 5])


# Q8. 2D Slicing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the first two rows.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [34]:
# Write your code here
arr = np.arange(1,10).reshape(3,3)
arr[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])


# Q9. 2D Slicing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the first two columns of all rows.

## Sample Output
```python
[[10 20]
 [40 50]
 [70 80]]
```


In [45]:
# Write your code here
arr = np.arange(10,91,10).reshape(3,3)
arr[:,:2]

array([[10, 20],
       [40, 50],
       [70, 80]])


# Q10. Boolean Indexing

## Problem Statement
Create the array:

```python
[5, 12, 18, 25, 30, 7]
```

Print only the values greater than 15.

## Sample Output
```python
[18 25 30]
```


In [49]:
# Write your code here
arr = np.array([5, 12, 18, 25, 30, 7])
bool_indexing =arr[arr > 15]
bool_indexing

array([18, 25, 30])