# NumPy Matrix + Pandas Assignment


## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [ ]:
# Write your code here
import numpy as np
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```


In [ ]:
# Write your code here
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = matrix * 2

print(result)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```


In [ ]:
# Write your code here
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr =np.sum(matrix,axis=1)
print(arr)

[ 6 15 24]


## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```


In [ ]:
# Write your code here
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr =np.sum(matrix,axis=0)
print(arr)

[12 15 18]


## Q5. Extract Second Row

### Output
```python
[4 5 6]
```


In [ ]:
# Write your code here
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr =matrix[1]
print(arr)

[4 5 6]


## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |


In [ ]:
# Write your code here
import pandas as pd
data = {
    "Name" :["Raj","Amit","Neha","Priya"],
    "Marks" : [80,70,90,85]
}
df=pd.DataFrame(data)
df

,Name,Marks
0,Raj,80
1,Amit,70
2,Neha,90
3,Priya,85


## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```


In [ ]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 70, 90, 85]
}

df = pd.DataFrame(data)

df["Bonus"] = df["Marks"] + 5

print(df)

    Name  Marks  Bonus
0    Raj     80     85
1   Amit     70     75
2   Neha     90     95
3  Priya     85     90


## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```


In [5]:
# Write your code here
import pandas as pd
data ={
    "Name" : ["Neha","Priya"],
    "Score" : [90,85]
}
df = pd.DataFrame(data)
print(df[df["Score"] > 80])




    Name  Score
0   Neha     90
1  Priya     85


## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```


In [9]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 70, 90, 85]
}

df = pd.DataFrame(data)
print(df.iloc[0])

Name     Raj
Marks     80
Name: 0, dtype: object


## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```


In [11]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 70, 90, 85]
}

df = pd.DataFrame(data)
print(df.iloc[2:3])

   Name  Marks
2  Neha     90


## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```


In [13]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 70, 90, 85]
}

df = pd.DataFrame(data)
print(df.iloc[0:2])

   Name  Marks
0   Raj     80
1  Amit     70


## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```


In [14]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 70, 90, 85]
}

df = pd.DataFrame(data)
print(df["Name"])

0      Raj
1     Amit
2     Neha
3    Priya
Name: Name, dtype: object


## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```


In [17]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 70, 90, 85]
}

df = pd.DataFrame(data)
df["Marks"] == df["Marks"].replace(70,75)
print(df)

    Name  Marks
0    Raj     80
1   Amit     70
2   Neha     90
3  Priya     85


## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```


In [18]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Raj", "Amit", "Neha", "Priya"],
    "Marks": [80, 75, 90, 85]
}

df = pd.DataFrame(data)

df = df.sort_values(by="Marks", ascending=False)

print(df)

    Name  Marks
2   Neha     90
3  Priya     85
0    Raj     80
1   Amit     75
